vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profiles:
            uri_prefix: /media/rooms
            upload_destination: '%kernel.project_dir%/public/media/rooms'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        avatars:
            uri_prefix: /media/avatars
            upload_destination: '%kernel.project_dir%/public/media/avatars'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
